module Fetcher
  module Config
    MAX_FEED_SIZE = 10 * 1024 * 1024

    MAX_LIMIT = 1000
    DEFAULT_LIMIT = 100

    DEFAULT_CONNECT_TIMEOUT = 10.seconds
    DEFAULT_READ_TIMEOUT = 30.seconds

    DEFAULT_CIRCUIT_BREAKER_THRESHOLD = 5
    DEFAULT_CIRCUIT_BREAKER_TIMEOUT = 60.seconds

    DEFAULT_RATE_LIMIT_CAPACITY = 10.0
    DEFAULT_RATE_LIMIT_REFILL_RATE = 1.0

    DEFAULT_MAX_RETRIES = 3
    DEFAULT_RETRY_BASE_DELAY = 1.second
    DEFAULT_RETRY_MAX_DELAY = 30.seconds
    DEFAULT_RETRY_EXPONENTIAL_BASE = 2.0

    DEFAULT_MAX_CONCURRENT = 16

    REDDIT_MAX_POSTS_PER_REQUEST = 25
  end
end
